version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tempconverter-net
    deploy:
      placement:
        constraints:
          - node.role == manager
    secrets:
      - mysql_root_password
      - mysql_password
      - db_user
      - db_name

  web:
    image: dmatahl/devopsproject:latest
    ports:
      - "80:5000"
    environment:
      DB_USER_FILE: /run/secrets/db_user
      DB_PASS_FILE: /run/secrets/mysql_password
      DB_HOST: db
      DB_NAME_FILE: /run/secrets/db_name
      STUDENT_FILE: /run/secrets/student
      COLLEGE_FILE: /run/secrets/college
    networks:
      - tempconverter-net
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
    secrets:
      - mysql_password
      - db_user
      - db_name
      - student
      - college

volumes:
  db_data:

networks:
  tempconverter-net:

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
  db_user:
    external: true
  db_name:
    external: true
  student:
    external: true
  college:
    external: true
