version: '3.8'

services:
  db:
    image: docker.io/library/mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - STUDENT=${STUDENT}
      - COLLEGE=${COLLEGE}
    env_file:
      - .env

volumes:
  db_data:
