apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tempconverter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "super_strong_password"  # Use the actual root password here
        - name: MYSQL_DATABASE
          value: "super_important_db_name"  # Use the actual database name here
        - name: MYSQL_USER
          value: "serius_admin"  # Use the actual username here
        - name: MYSQL_PASSWORD
          value: "super_strong_password"  # Use the actual password here
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql  # Change the name to 'db' to match your other environment
  namespace: tempconverter
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql