# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tempconverter-secrets
  namespace: tempconverter
type: Opaque
data:
  DB_USER: c2VyaXVzX2FkbWlu  # base64 encoded
  DB_PASS: c3VwZXJfc3Ryb25nX3Bhc3N3b3Jk  # base64 encoded
  DB_HOST: ZGI=  # base64 encoded
  DB_NAME: c3VwZXJfaW1wb3J0YXRfZGJfbmFtZQ==  # base64 encoded
  STUDENT: RG9taW5payAg  # base64 encoded
  COLLEGE: QUxHRUJSQQ==  # base64 encoded

