# tempconverter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
  namespace: tempconverter
  labels:
    app: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
      - name: tempconverter
        image: docker.io/dmatahl/devopsproject:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "serius_admin"
        - name: DB_PASS
          value: "super_strong_password"
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "super_important_db_name"
        - name: STUDENT
          value: "Dominik"
        - name: COLLEGE
          value: "ALGEBRA"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tempconverter
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: tempconverter
  namespace: tempconverter
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: tempconverter
  type: LoadBalancer