# tempconverter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
  labels:
    app: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
      - name: tempconverter
        image: dmatahl/devopsproject:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: tempconverter-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: tempconverter-secrets
              key: DB_PASS
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: tempconverter-secrets
              key: DB_NAME
        - name: STUDENT
          valueFrom:
            secretKeyRef:
              name: tempconverter-secrets
              key: STUDENT
        - name: COLLEGE
          valueFrom:
            secretKeyRef:
              name: tempconverter-secrets
              key: COLLEGE
---
apiVersion: v1
kind: Service
metadata:
  name: tempconverter
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: tempconverter
  type: LoadBalancer
